services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3030:3000'
    volumes:
      - .:/app
      - /app/node_modules
      # - ./.next:/app/.next
    environment:
      - NODE_ENV=${NODE_ENV}
      - RESEND_API_KEY=${RESEND_API_KEY}
      - EMAIL=${EMAIL}
